apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-python.fullname" . }}-config
  labels:
    {{- include "k8s-python.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.APP_ENV | quote }}
  APP_VERSION: {{ .Values.config.APP_VERSION | quote }}
  PYTHONUNBUFFERED: {{ .Values.config.PYTHONUNBUFFERED | quote }}
